name: Receiver
 
on:
  repository_dispatch:
    types: [post_uploaded]
 
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: A event received
        run: |
          echo "A event received"
      - name: Update remote and push to origin
        run: |
            repo="https://2chanhaeng:${{secrets.pat}}@github.com/chomu37.github.io.git"
            git clone $repo
            cd chomu37.github.io
            git remote update
            git pull origin main