name: Trigger Target Workflow

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
        curl -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{ secrets.pat }}" \
        --request POST \
        --data '{"event_type": "post_uploaded", "client_payload": {}}' \
        https://api.github.com/repos/2chanhaeng/chomu37.github.io/dispatches