name: Upload Post

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Upload Post
        run: |
          git clone https://2chanhaeng:${{ secrets.pat }}@github.com/2chanhaeng/chomu37.github.io.git
          cd chomu37.github.io
          git remote add posts https://2chanhaeng:${{ secrets.pat }}@github.com/2chanhaeng/blog-posts.git
          git subtree add --prefix=_posts posts main
          git subtree pull --prefix=_posts posts main -m "post uploaded"
          git remote update
          git pull origin main
